name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
          deta-access-token: 'ViJbaJGb_Rcth73b2H7M6fEjWuEbhseuCcGd8HAaa' #Deta access token https://docs.deta.sh/docs/cli/auth
          deta-name: 'remix-deta'
          deta-project: 'default'
          deta-project-dir: '.'
      - run: npm install
      - name: Build Remix App
        shell: bash
        run: |
          npm run build
          
      - name: Install Deta CLI
        shell: bash
        run: |
          curl -fsSL https://get.deta.dev/cli.sh | sh

      - name: Clone Deta Metadata
        shell: bash
        run: |
          export DETA_ACCESS_TOKEN=${{ deta-access-token }}
          cd ${{ deta-project-dir }}
          ~/.deta/bin/deta clone --name ${{ deta-name }} --project ${{ deta-project }} tmp/
          cp -r tmp/.deta .

      - name: Deploy to Deta
        shell: bash
        run: |
          export DETA_ACCESS_TOKEN=${{ deta-access-token }}
          cd ${{ deta-project-dir }}
          ~/.deta/bin/deta deploy